spring:
  application:
    name: ${springboot.app.name:apiservice}
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: user.exchange
    routingkey: user.routingkey
server:
  port: 8081